import { createElement } from '@lwc/engine-dom';
import FatherCompCustomEventJs from 'c/fatherCompCustomEventJs';

describe('c-father-comp-custom-event-js', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-father-comp-custom-event-js', {
            is: FatherCompCustomEventJs
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});