name: GitHubDeployProcess
on: 
    push: 
        branches: [master]

jobs:
    CI:
        runs-on: ubuntu-latest
        container: 
            image: salesforce/cli:2.79.0-full
        steps:
            - uses: actions/checkout@v2
            - name: VALIDATE PACKAGE
              run: | 
                echo force://${{secrets.CLI_APP}}::${{secrets.USER_TOKEN}}@${{secrets.SF_URL}} >> config/auth.txt
                sf force:auth:sfdxurl:store -f config/auth.txt -s -a MyOrg
                sf force:org:create -f config/project-scratch-def.json -a CIOrg -s -v MyOrg
                sf force:source:push -u CIOrg
                sf force:apex:test:run -l RunLocalTests -u CIOrg -c -r human -w 2 --verbose
                sf force:org:delete -u CIOrg -p