name: GitHubDeployProcess
on: 
    push: 
        branches: [master]

jobs:
    CI:
        runs-on: ubuntu-latest
        container: 
            image: salesforce/cli:2.79.0-full
        steps:
            - uses: actions/checkout@v4

            - name: TESTING
              run: | 
                echo force://${{secrets.CLI_APP}}::${{secrets.USER_TOKEN}}@${{secrets.SF_URL}} >> config/auth.txt
                sf org login sfdx-url --sfdx-url-file config/auth.txt --set-default --alias MyOrg
                sf org create scratch --definition-file config/project-scratch-def.json --alias CIOrg --set-default --target-dev-hub MyOrg
                sf project deploy start --target-org CIOrg
                sf apex run test --target-org CIOrg --test-level RunLocalTests --wait 2 --result-format human --code-coverage
                sf org delete scratch --target-org CIOrg --no-prompt
    
    CD:
        needs: [CI]
        runs-on: ubuntu-latest
        container: 
            image: salesforce/cli:2.79.0-full
        steps:
            - uses: actions/checkout@v2

            - name: DEPLOY
              run: |
                    echo force://${{secrets.CLI_APP}}::${{secrets.USER_TOKEN}}@${{secrets.SF_URL}} >> config/auth.txt
                    sf org login sfdx-url --sfdx-url-file config/auth.txt --set-default --alias MyOrg
                    sf project deploy start --source-dir "force-app/main/default" --target-org MyOrg --wait 2 --verbose

            